name: delivery_app
description: تطبيق التوصيل.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # إدارة الحالة
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  
  # الخرائط والموقع
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  
  # الشبكة والاتصال
  http: ^1.3.0
  connectivity_plus: ^5.0.2
  # التخزين المحلي
  flutter_secure_storage: ^9.0.0
  # Firebase حزم
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  cloud_firestore: ^4.13.6
  firebase_crashlytics: ^3.4.8
  firebase_storage: ^11.5.6
  # إشعارات وتخزين محلي
  flutter_local_notifications: ^16.3.0
  overlay_support: ^2.0.0
  shared_preferences: ^2.2.2
  # واجهة المستخدم
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  
  # إضافة تبعيات مفقودة
  equatable: ^2.0.5
  dartz: ^0.10.1
  # الحزم المشتركة في المونوربو
  models:
    path: ../shared_modules/models
  services:
    path: ../shared_modules/services
  widgets :
    path: ../shared_modules/widgets 
  shared_core:
    path: ../shared_core
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true
