name: seller_panel
description: تطبيق صاحب المتجر.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Added missing dependencies
  flutter_riverpod: any
  go_router: any
  firebase_core: any # Added for Firebase initialization
  # End of added dependencies

    # Firebase حزم
  firebase_auth: ^5.5.2
  firebase_messaging: any
  cloud_firestore: any

    # إشعارات وتخزين محلي
  overlay_support: ^2.0.0
  flutter_local_notifications: ^15.0.0
  shared_preferences: ^2.2.2

  # Charts
  fl_chart: ^0.62.0

  # واجهة المستخدم
  cached_network_image: ^3.3.1
  intl: ^0.20.2

  # HTTP requests
  http: ^1.3.0

  # الحزم المشتركة في المونوربو
  shared_models:
    path: ../shared_modules/shared_models
  shared_services:
    path: ../shared_modules/shared_services
  shared_widgets:
    path: ../shared_modules/shared_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
