name: seller_panel
description: تطبيق صاحب المتجر.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # إدارة الحالة
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.1
  
  # Firebase حزم
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_crashlytics: ^3.4.8
  # إشعارات وتخزين محلي
  overlay_support: ^2.0.0
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  # Charts
  fl_chart: ^0.65.0
  # واجهة المستخدم
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  # HTTP requests
  http: ^1.3.0
  
  # إضافة تبعيات مفقودة
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # الحزم المشتركة في المونوربو
  models:
    path: ../shared_modules/models
  services:
    path: ../shared_modules/services
  widgets :
    path: ../shared_modules/widgets 
  shared_core:
    path: ../shared_core
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
flutter:
  uses-material-design: true
  
  # إضافة دعم ملفات الترجمة
  generate: true
